// Copyright (c) FIRST and other WPILib contributors.
// Open Source Software; you can modify and/or share it under the terms of
// the WPILib BSD license file in the root directory of this project.

package frc.robot;

/**
 * The Constants class provides a convenient place for teams to hold robot-wide numerical or boolean
 * constants. This class should not be used for any other purpose. All constants should be declared
 * globally (i.e. public static). Do not put anything functional in this class.
 *
 * <p>It is advised to statically import this class (or one of its inner classes) wherever the
 * constants are needed, to reduce verbosity.
 */
public final class Constants {
  public static class LiftConstants{
    public static final double[] desiredHeight= new double[]{
      0.00,//normal height
      0.46,//L1
      0.81,//L2
      1.21,//L3
      1.83 //L4
    };
    public static final double gearRatio=256;
    public static final double rotationConversionFactor=2*Math.PI/gearRatio;
    //to ensure the arm doesn't tear itself apart. 
    public static final double maxPower=0.2;

    public static enum Height{
      Ground,
      L1,
      L2,
      L3,
      L4
    }
    //arm length is 29 inches?
    public static final double armLength=29*0.0254;
    public static final double kPLift=0.2;
    public static final double kILift=0.0;
    public static final double kDLift=0.0;
    public static final double angleTolerance=90/Math.PI;
    //Minimuum power required to overcome moment generated by weight of system. Remember that this is further scaled by maxPower
    public static final double kWeightMomentOffsetFactor=0.25;
  }
  public static class OperatorConstants {
    public static final int kDriverControllerPort = 0;
  }
}
